// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Button: typeof import("./src/components/Button/index.vue")["default"];
    "Button.index": typeof import("./src/components/Button/Button.index.vue")["default"];
    "Com.link.index": typeof import("./src/components/Link/com.link.index.vue")["default"];
    "Com.table.index": typeof import("./src/components/Table/com.table.index.vue")["default"];
    "Component.link": typeof import("./src/components/Link/component.link.vue")["default"];
    "Component.link.index": typeof import("./src/components/Link/component.link.index.vue")["default"];
    "Component.table": typeof import("./src/components/Table/component.table.vue")["default"];
    "Component.table.index": typeof import("./src/components/Table/component.table.index.vue")["default"];
    "Dialog.container.index": typeof import("./src/components/DialogContainer/dialog.container.index.vue")["default"];
    "Dialog.index": typeof import("./src/components/Dialog/dialog.index.vue")["default"];
    "Dialog.item": typeof import("./src/components/Dialog/dialog.item.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioButton: typeof import("element-plus/es")["ElRadioButton"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    "FormGenerator.index": typeof import("./src/components/FormGenerator/formGenerator.index.vue")["default"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    IEpMoon: typeof import("~icons/ep/moon")["default"];
    IEpOperation: typeof import("~icons/ep/operation")["default"];
    IEpOperations: typeof import("~icons/ep/operations")["default"];
    IEpTools: typeof import("~icons/ep/tools")["default"];
    "Link.index": typeof import("./src/components/Link/Link.index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    "Table.index": typeof import("./src/components/Table/Table.index.vue")["default"];
  }
}

export {};
